keys:
  - &tonychg age1a2s2p7h54acqp7j0xhwu32ea8wkdt54dxfy5yax38pcdrff7ae8qc63zhl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *tonychg
